version: 2
jobs:
  build:
    working_directory: ~/2d
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install NPM
          command: |
            node -v
            npm -v
            NODE_ENV=development npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: code-lint
          command: |
            mkdir ./reports
            npm run lint -- --formatters-dir node_modules/tslint-junit-formatter/formatters --format junit src/**/*.ts -o ./reports/eslint.xml
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc npm run test:mocha.ci'
          environment:
            MOCHA_FILE: /tmp/test-results/test-results.xml
      - run:
          name: build
          command: 'npm run build:prod'
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_artifacts:
          path: reports
          prefix: reports
      - type: setup-docker-engine
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run hello-world
      - run:
          name: Build Docker image
          command: |
            TAG="latest"
            docker build --rm=false -t d3trax/2d-game:$TAG .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push d3trax/2d-game:$TAG

              LOCAL_USERNAME=`git log -n 1 --pretty=format:"%ae"`
              REVISION=`git log -n 1 --pretty=format:"%H"`
              curl https://api.rollbar.com/api/1/deploy/ \
                -F access_token=$ROLLBAR_ACCESS_TOKEN \
                -F environment=$NODE_ENV \
                -F revision=$REVISION \
                -F local_username=$LOCAL_USERNAME
            fi
